run scenarios.json nested within a ./test/<feature> folder
devcontainers/cli pull request #124
Opened 2022-08-12 20:16 UTC by joshspicer

Allows for more flexibility in asserting a range of options for a given feature.  It builds upon the existing `--scenarios`, allowing scenarios to be scoped to features. 

The main advantage of this is that in CI, we can only run scenarios where the code has been touched.  The [current, single scenario test takes 40 minutes to run right now](https://github.com/devcontainers/features/runs/7809178393?check_suite_focus=true).  This change will let us scope scenarios to individual features, when it makes sense.

The existing `--scenarios` flag will stick around, and is useful for asserting scenarios that span > 1 feature.  A later improvement should find a way to improve run time for those cases.

## Example 

Each feature (eg: `dotnet`) can provide a list of possible scenarios scoped to the feature itself.  This is useful for testing different options for a single feature.

```
@joshspicer ➜ ~/features/test/dotnet (main ✗) $ tree
.
├── install_additional_dotnet.sh
├── scenarios.json
└── test.sh
```

The `scenarios.json` file in this case would be an object of an arbitrary number of labelled dev container configs, representing test cases.

```json
{
"install_additional_dotnet": {
      "image": "ubuntu:focal",
      "features": {
      "dotnet": {
                  "version": "6.0.301",
                  "additionalVersions": "5.0,3.1.420"
      }
   },
   "..." : {}
}
```

The `features test` command will create a container for **each** scenario based on the declared dev container config, and then assert that an accompanying shell script (named the same as the label (in this case, `install_additional_dotnet.sh`), exits with a zero exit code.

Additionally, a test case will be always be autogenerated with no options (an empty object, `{}`) passed.

At the end, a summary of the results of both the auto-generated test, and each scenario ran, will be printed at the bottom of the test.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/23246594/184435801-69e7c0a4-1f38-4d14-8178-654851aaa719.png">

If any test fails, the CLI will exit with a non-zero exit code, otherwise it will exit with a 0 exit code.

2022-08-16 21:55 UTC, jungaretti commented
This change would make it much easier and faster to test a feature's options (version, add-ons, etc.)

2022-08-23 08:57 UTC, chrmarti requested changes

2022-08-23 08:57 UTC, chrmarti commented on src/spec-node/featuresCLI/test.ts
> +			'skip-scenarios': { type: 'boolean', default: false, description: 'Skip all \'scenario\' style tests under  Cannot be combined with \'-global--scenarios-only\'.' },
Description seems to be missing a word or two after 'under'? '-global--scenarios-only' has a misplaced dash.

2022-08-23 08:57 UTC, chrmarti commented on src/spec-node/featuresCLI/test.ts
> +			'features': { type: 'array', alias: 'f', describe: 'Feature(s) to test as space-separated parameters. Omit to run all tests.  Cannot be combined with \'--global-scenarios-only\'.', },
Can you add `conflicts: ['global-scenarios-only']`? (Haven't tried that yet.)

2022-08-23 12:00 UTC, joshspicer commented
i'm seeing the `conflicts` statement blocking when it shouldn't, probably since `--global-scenarios-only` has a default value of false.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/23246594/186152411-c42a0cfd-8e41-4442-a945-2cbec5b6650f.png">

I think we're covered by the `.check(...)` statements on lines 24-31, so I'm going to leave out conflicts (unless there's another reason to add that over the checks I previously had)

2022-08-23 12:04 UTC, chrmarti approved these changes
LGTM!

2022-08-23 15:19 UTC, joshspicer commented
Validated by manually running build against features repo (using updated commands as seen in https://github.com/devcontainers/features/pull/114)

2022-08-23 15:20 UTC, merged