validate input of getRef()
devcontainers/cli pull request #293
Opened 2022-11-21 23:51 UTC by joshspicer

relevant: https://github.com/oras-project/oras/issues/679

2022-11-22 22:54 UTC, samruddhikhandale submitted a review, later dismissed

2022-11-23 07:52 UTC, chrmarti requested changes

2022-11-23 07:52 UTC, chrmarti commented on src/spec-configuration/containerCollectionsOCI.ts
> +const regexForPath = /[a-z0-9]+([._-][a-z0-9]+)*(\/[a-z0-9]+([._-][a-z0-9]+)*)*/;
Add `^` and `$` to the two regexes to make sure they match the entire string and not just a substring?

2022-11-28 15:17 UTC, chrmarti approved these changes
LGTM!

2022-11-28 15:22 UTC, merged