Testing Quality of Life Improvements
devcontainers/cli pull request #312
Opened 2022-12-02 19:45 UTC by greggroth

As someone new to typescript and not very familiar with the tooling and best practices, I struggled to get up-and-running with the project 😅 . I've included configuration for the Mocha Sidebar VS Code extension that is [recommended by the Mocha project](https://mochajs.org/#mocha-sidebar-vs-code) and simple instructions in the README for getting a green test suite after cloning or opening the project in a Codespace.

2022-12-06 18:06 UTC, joshspicer approved these changes
Very helpful, thanks!

2022-12-07 14:31 UTC, chrmarti requested changes
Thanks! Left a comment regarding prettier.

2022-12-08 18:11 UTC, greggroth commented on package.json
> +		"prettier": "^2.8.0",
It's opinionated, but configurable https://github.com/devcontainers/cli/pull/312/files#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2

I don't have a strong feeling about which formatter is used if you prefer another, but I think having one would be beneficial. For example, as I was working in the codebase I found I was fighting with VS Code to match the existing code format. Use Prettier means contributors don't have to think about that.

2022-12-08 18:21 UTC, greggroth commented on package.json
> +		"prettier": "^2.8.0",
Here's an example of two json files with completely different indentations (tabs v spaces and size):

https://github.com/devcontainers/cli/blob/main/.vscode/settings.json
https://github.com/devcontainers/cli/blob/main/src/test/configs/image-metadata/.devcontainer/devcontainer.json

2023-04-04 19:43 UTC, greggroth commented
Closing since it's stale. We can grab all or parts of this if there's still interest in the future.

2023-04-04 19:44 UTC, closed without merging