Docs for `templates apply` command
devcontainers/cli pull request #388
Opened 2023-01-30 22:41 UTC by joshspicer

2023-01-30 22:44 UTC, samruddhikhandale approved these changes
Awesome!

2023-01-31 14:31 UTC, chrmarti requested changes
👍 Left a request.

2023-01-31 14:31 UTC, chrmarti commented on docs/templates/apply.md
> +![example](https://user-images.githubusercontent.com/23246594/215609996-c1109c72-1a05-410e-83a6-86a782cce929.png)
I suggest to add the output as text, not as screenshot.

2023-02-02 13:50 UTC, chrmarti approved these changes
Great, thanks!

2023-02-02 16:47 UTC, merged