create an output object to capture docker-compose cli logging
devcontainers/cli pull request #538
Opened 2023-05-23 23:54 UTC by joshspicer

fixes https://github.com/devcontainers/cli/issues/535

Similar to the in the `catch` below this change, create a new

2023-05-24 06:21 UTC, chrmarti requested changes

2023-05-24 06:21 UTC, chrmarti commented on src/spec-node/dockerCompose.ts
> +				output: makeLog({
`makeLog(params.output, LogLevel.Info)` should do it (dimensions are not used when running without PTY).

2023-05-25 07:34 UTC, chrmarti approved these changes
Thanks!

2023-05-25 10:06 UTC, Maxxie992 approved these changes

2023-05-25 16:04 UTC, merged