Recreate `features` entry of lockfile with `features upgrade` command
devcontainers/cli pull request #645
Opened 2023-09-25 21:49 UTC by joshspicer

Provides a way to programmatically regenerate the dev container lockfile without building the dev container or deleting the lockfile.  This may be useful in CI scenarios where you'd like to programmatically upgrade a lockfile, and then build an image based on it.

This command also provides a way to initialize a lockfile programatically with the `--init-lockfile` flag.

## Usage

```sh
$ devcontainer features upgrade \
       --workspace-folder /workspaces/project
[4 ms] @devcontainers/cli 0.51.3. Node.js v16.20.0. linux 5.15.0-1041-azure x64.
Upgrading lockfile...

$ cat /workspaces/project/.devcontainer-lock.json
{
  "features": {
    "ghcr.io/codspace/features/color:1.0.4": {
      "version": "1.0.4",
      "resolved": "ghcr.io/codspace/features/color@sha256:6e9d07c7f488fabc981e7508d8c25eea4b102ebe4b87f9fc6f233efa1d325908",
      "integrity": "sha256:6e9d07c7f488fabc981e7508d8c25eea4b102ebe4b87f9fc6f233efa1d325908"
    },
...
}
```

2023-09-26 13:47 UTC, chrmarti requested changes

2023-09-26 13:47 UTC, chrmarti commented on src/spec-node/featuresCLI/upgrade.ts
> +		if (!initLockfile && !(await cliHost.isFile(lockfilePath))) {
Or just write the lockfile when it does not exist yet? That way we don't need the `--init-lockfile` option.

2023-09-26 15:04 UTC, joshspicer commented on src/spec-node/devContainersSpecCLI.ts
> +		y.command('upgrade', 'Upgrade Features by rewriting lockfile', featuresUpgradeOptions, featuresUpgradeHandler);
sounds good, that makes sense to me

2023-09-29 08:28 UTC, chrmarti approved these changes
Great, thanks!

2023-09-29 16:25 UTC, merged