Feat: add generate-docs subcommand
devcontainers/cli pull request #759
Opened 2024-02-16 05:55 UTC by hellodword

Discussed with @samruddhikhandale in this issue: https://github.com/devcontainers/action/issues/212

And added a `test-container-features-cli` script for fast test, the `test-container-features` costs a lot of time locally.

2024-02-17 00:26 UTC, samruddhikhandale requested changes
This is super cool, thank you so much for taking the time to contribute this change 🎉 

Works like a charm! 

![image](https://github.com/devcontainers/cli/assets/24955913/16d9fc83-4cae-42f3-98ff-427900e6f75d)

2024-02-22 00:37 UTC, samruddhikhandale approved these changes
Amazing, let's wait for another review from @chrmarti 
Thanks again! 🎉

2024-03-07 07:51 UTC, chrmarti approved these changes
LGTM, thanks!

2024-03-08 18:20 UTC, samruddhikhandale approved these changes

2024-03-11 16:36 UTC, merged