solution to cli issue - TypeError: Cannot read properties of undefined (reading 'fsPath') #895
devcontainers/cli pull request #924
Opened 2024-10-28 23:35 UTC by gauravsaini04

ref: #895 

**Description**
* The pr is raised as a solution to the issue `TypeError: Cannot read properties of undefined (reading 'fsPath')` #895.

2024-10-29 08:53 UTC, chrmarti requested changes
Good catch, left a comment for a possible improvement.

2024-10-30 10:27 UTC, gauravsaini04 commented on src/spec-node/featuresCLI/resolveDependencies.ts
> +	let configObj: DevContainerConfig | string = config.hasOwnProperty('configFilePath') && config.configFilePath ? config : configPath;
have implemented as you had suggested, need another review from you

2024-10-31 08:00 UTC, chrmarti requested changes
Looks good, one small ask, otherwise ready for merging. Thanks.

2024-10-31 08:22 UTC, gauravsaini04 commented on src/spec-node/featuresCLI/resolveDependencies.ts
> +	const configFile: URI | undefined = configPath ? URI.file(path.resolve(process.cwd(), configPath)) : undefined;
thanks ! made changes..

2024-11-01 10:03 UTC, chrmarti approved these changes
LGTM!

2024-11-05 19:26 UTC, joshspicer approved these changes

2024-11-08 03:46 UTC, gauravsaini04 commented
> LGTM!

Hi @chrmarti, as I don't have merging authorization, could you pls merge this

2024-11-21 15:32 UTC, eljog approved these changes

2024-11-21 15:32 UTC, merged